-- Account-scoped notifications generated by trusted database events.
create table if not exists public.app_notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id text not null references public.profiles(id) on delete cascade,
  actor_id text references public.profiles(id) on delete set null,
  actor_name text,
  actor_avatar text,
  type text not null check (type in ('story_like', 'profile_like', 'match', 'message', 'verification')),
  entity_id text,
  title text not null,
  body text not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  read_at timestamptz
);

create index if not exists app_notifications_recipient_idx
  on public.app_notifications (recipient_id, created_at desc);

alter table public.app_notifications enable row level security;

drop policy if exists "Users can read their own notifications" on public.app_notifications;
create policy "Users can read their own notifications"
  on public.app_notifications for select to authenticated
  using (auth.uid()::text = recipient_id);

drop policy if exists "Users can mark their own notifications read" on public.app_notifications;
create policy "Users can mark their own notifications read"
  on public.app_notifications for update to authenticated
  using (auth.uid()::text = recipient_id)
  with check (auth.uid()::text = recipient_id);

revoke all on table public.app_notifications from anon, authenticated;
grant select, update on table public.app_notifications to authenticated;

create or replace function public.notify_story_like()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id text;
  v_actor_name text;
  v_actor_avatar text;
begin
  select s.user_id into v_owner_id
  from public.campus_stories s
  where s.id = new.story_id;

  if v_owner_id is null or v_owner_id = new.user_id then
    return new;
  end if;

  select p.name, coalesce(p.photos[1], '')
    into v_actor_name, v_actor_avatar
  from public.profiles p
  where p.id = new.user_id;

  insert into public.app_notifications (recipient_id, actor_id, actor_name, actor_avatar, type, entity_id, title, body)
  values (
    v_owner_id,
    new.user_id,
    coalesce(v_actor_name, 'A UniAbuja student'),
    nullif(v_actor_avatar, ''),
    'story_like',
    new.story_id,
    'Someone liked your story',
    coalesce(v_actor_name, 'A UniAbuja student') || ' liked your campus story.'
  );
  return new;
end;
$$;

drop trigger if exists campus_story_like_notification on public.campus_story_likes;
create trigger campus_story_like_notification
after insert on public.campus_story_likes
for each row execute function public.notify_story_like();

create or replace function public.notify_profile_like()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_name text;
  v_actor_avatar text;
begin
  select p.name, coalesce(p.photos[1], '')
    into v_actor_name, v_actor_avatar
  from public.profiles p
  where p.id = new.sender_id;

  if new.sender_id = new.recipient_id then
    return new;
  end if;

  insert into public.app_notifications (recipient_id, actor_id, actor_name, actor_avatar, type, entity_id, title, body)
  values (
    new.recipient_id,
    new.sender_id,
    coalesce(v_actor_name, 'A UniAbuja student'),
    nullif(v_actor_avatar, ''),
    'profile_like',
    new.sender_id,
    case when new.like_type = 'super_like' then 'You received a Super Like' else 'You received a new Like' end,
    coalesce(v_actor_name, 'A UniAbuja student') || case when new.like_type = 'super_like' then ' sent you a Super Like.' else ' liked your profile.' end
  );
  return new;
end;
$$;

drop trigger if exists profile_like_notification on public.profile_likes;
create trigger profile_like_notification
after insert on public.profile_likes
for each row execute function public.notify_profile_like();

create or replace function public.notify_match()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_name text;
  v_user_avatar text;
  v_other_name text;
  v_other_avatar text;
begin
  select p.name, coalesce(p.photos[1], '') into v_user_name, v_user_avatar
  from public.profiles p where p.id = new.user_id_1;
  select p.name, coalesce(p.photos[1], '') into v_other_name, v_other_avatar
  from public.profiles p where p.id = new.user_id_2;

  insert into public.app_notifications (recipient_id, actor_id, actor_name, actor_avatar, type, entity_id, title, body)
  values
    (new.user_id_1, new.user_id_2, v_other_name, nullif(v_other_avatar, ''), 'match', new.id, 'It’s a Match', coalesce(v_other_name, 'A student') || ' matched with you.'),
    (new.user_id_2, new.user_id_1, v_user_name, nullif(v_user_avatar, ''), 'match', new.id, 'It’s a Match', coalesce(v_user_name, 'A student') || ' matched with you.');
  return new;
end;
$$;

drop trigger if exists match_notification on public.matches;
create trigger match_notification
after insert on public.matches
for each row execute function public.notify_match();

create or replace function public.notify_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recipient_id text;
  v_actor_name text;
  v_actor_avatar text;
  v_preview text;
begin
  select case when m.user_id_1 = new.sender_id then m.user_id_2 else m.user_id_1 end
    into v_recipient_id
  from public.matches m where m.id = new.match_id;
  if v_recipient_id is null then return new; end if;

  select p.name, coalesce(p.photos[1], '') into v_actor_name, v_actor_avatar
  from public.profiles p where p.id = new.sender_id;
  v_preview := case when coalesce(new.image_url, '') <> '' then 'Sent you a photo.' else left(nullif(new.text, ''), 90) end;

  insert into public.app_notifications (recipient_id, actor_id, actor_name, actor_avatar, type, entity_id, title, body)
  values (v_recipient_id, new.sender_id, v_actor_name, nullif(v_actor_avatar, ''), 'message', new.match_id, 'New message', coalesce(v_actor_name, 'A match') || ': ' || coalesce(v_preview, 'Sent you a message.'));
  return new;
end;
$$;

drop trigger if exists message_notification on public.messages;
create trigger message_notification
after insert on public.messages
for each row execute function public.notify_message();

create or replace function public.notify_verification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_body text;
begin
  if old.status is not distinct from new.status or new.status not in ('approved', 'rejected') then
    return new;
  end if;
  v_body := case when new.status = 'approved' then 'Your UniAbuja identity verification was approved.' else 'Your verification needs attention: ' || coalesce(new.admin_note, 'Please review your submission and try again.') end;

  insert into public.app_notifications (recipient_id, type, entity_id, title, body)
  values (new.user_id, 'verification', new.id, case when new.status = 'approved' then 'Verification approved' else 'Verification update' end, v_body);
  return new;
end;
$$;

drop trigger if exists verification_notification on public.verification_requests;
create trigger verification_notification
after update of status on public.verification_requests
for each row execute function public.notify_verification();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'app_notifications'
  ) then
    alter publication supabase_realtime add table public.app_notifications;
  end if;
end;
$$;
